export type {
  StyleConfig,
  PointBinding,
  ComponentTemplate,
  ScadaComponentMeta,
  ComponentConfig,
  BaseComponentConfig,
  GaugeConfig,
  ChartConfig,
  IndicatorConfig,
  SwitchConfig,
  SliderConfig,
  TextConfig,
  ButtonConfig,
  ImageConfig,
  TextComponentConfig,
  NumberComponentConfig,
  WriteValueComponentConfig,
  EnumValueComponentConfig,
  EnumValueItem,
  LineComponentConfig,
  ArcComponentConfig,
  IconComponentConfig,
  GaugeComponentConfig,
  ChartComponentConfig,
  LineChartComponentConfig,
  LineChartDataPoint,
  IndicatorComponentConfig,
  SwitchComponentConfig,
  SliderComponentConfig,
  SliderSwitchComponentConfig,
  SliderBarItemConfig,
  SliderBarComponentConfig,
  ImageComponentConfig,
  ButtonComponentConfig,
  AcModeComponentConfig,
  AcFanSpeedComponentConfig,
  ValueImageItem,
  ValueImageSwitchComponentConfig,
  NavButtonComponentConfig,
  PopupComponentConfig,
  ScadaComponent,
  PanelType,
  ScadaPanel
} from '@/views/ScadaEditor/types'

export type { ComponentType } from '@/views/ScadaEditor/registry'

export { COMPONENT_TEMPLATES } from '@/views/ScadaEditor/registry'